# Generated by Django 5.2.7 on 2025-11-15 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('solves', models.CharField(max_length=200)),
                ('text', models.TextField()),
            ],
            options={
                'permissions': [('add_posts', 'Can add and edit posts')],
            },
        ),
    ]
